"""RAG-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IA3y28vxPqiYiBszBGCwRbI57Ie34GrO
"""

# Commented out IPython magic to ensure Python compatibility.

from langchain_huggingface import HuggingFaceEmbeddings
from dotenv import load_dotenv
from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from urllib.parse import urlparse, parse_qs
from youtube_transcript_api import (YouTubeTranscriptApi,TranscriptsDisabled,NoTranscriptFound)
from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

import os
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
print("API key loaded:", api_key is not None)

def extract_video_id(url):
    parsed_url = urlparse(url)

    # Normal URL:
    # https://www.youtube.com/watch?v=Gfr50f6ZBvo
    if parsed_url.hostname in ["www.youtube.com", "youtube.com"]:
        return parse_qs(parsed_url.query).get("v", [None])[0]

    # Short URL:
    # https://youtu.be/Gfr50f6ZBvo
    if parsed_url.hostname == "youtu.be":
        return parsed_url.path.strip("/").split("?")[0]

    return None

video_url = input("Enter YouTube video URL: ")
video_id = extract_video_id(video_url)
print("Video ID:", video_id)
try:
    # If you don’t care which language, this returns the “best” one
    api = YouTubeTranscriptApi()
    transcript = api.fetch(video_id)
    transcript_list = transcript.to_raw_data()

    # Flatten it to plain text
    transcript = " ".join(chunk["text"] for chunk in transcript_list)
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")

transcript_list

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
vector_store = FAISS.from_documents(chunks, embeddings)

vector_store.index_to_docstore_id

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 4})

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    temperature=0.2
)

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parser = StrOutputParser()

main_chain = parallel_chain | prompt | llm | parser

question = input("Ask a question about the video: ")

answer = main_chain.invoke(question)

print("\nAnswer:")
print(answer)

# this is last of first one

# ============================================================
# YOUTUBE VIDEO ID
# ============================================================

def extract_video_id(url):

    parsed_url = urlparse(url)

    # Normal YouTube URL
    if parsed_url.hostname in [
        "www.youtube.com",
        "youtube.com"
    ]:
        return parse_qs(
            parsed_url.query
        ).get("v", [None])[0]

    # Short YouTube URL
    if parsed_url.hostname in [
        "youtu.be",
        "www.youtu.be"
    ]:
        return parsed_url.path.strip(
            "/"
        ).split("?")[0]

    return None

# ============================================================
# FETCH YOUTUBE TRANSCRIPT
# ============================================================

def get_transcript(video_id):

    api = YouTubeTranscriptApi()

    transcript_data = api.fetch(
        video_id
    )

    transcript_list = (
        transcript_data.to_raw_data()
    )

    transcript = " ".join(
        chunk["text"]
        for chunk in transcript_list
    )

    return transcript

# ============================================================
# CREATE VECTOR STORE
# ============================================================

def create_vector_store(transcript):

    # ----------------------------------------
    # Split transcript into chunks
    # ----------------------------------------

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200
    )

    chunks = splitter.create_documents(
        [transcript]
    )

    # ----------------------------------------
    # Create embeddings
    # ----------------------------------------

    embeddings = HuggingFaceEmbeddings(
        model_name=
        "sentence-transformers/"
        "all-MiniLM-L6-v2"
    )

    # ----------------------------------------
    # Create FAISS vector database
    # ----------------------------------------

    vector_store = FAISS.from_documents(
        chunks,
        embeddings
    )

    return vector_store

# ============================================================
# CREATE RAG CHAIN
# ============================================================

def create_rag_chain(vector_store):

    # ----------------------------------------
    # Create Retriever
    # ----------------------------------------

    retriever = (
        vector_store
        .as_retriever(
            search_type="similarity",
            search_kwargs={
                "k": 4
            }
        )
    )

    # ----------------------------------------
    # Get Gemini API Key
    # ----------------------------------------

    api_key = os.getenv(
        "GEMINI_API_KEY"
    )

    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY is not configured."
        )

    # ----------------------------------------
    # Gemini LLM
    # ----------------------------------------

    llm = ChatGoogleGenerativeAI(
        model="gemini-3.6-flash",
        temperature=0.2,
        google_api_key=api_key
    )

    # ----------------------------------------
    # Prompt
    # ----------------------------------------

    prompt = PromptTemplate(
        template="""
You are a helpful assistant.

Answer ONLY from the provided YouTube
transcript context.

Rules:
- Do not use outside knowledge.
- If the answer is not present in the transcript,
  say "I don't know based on this video."
- Give a clear and useful answer.

Transcript Context:
{context}

Question:
{question}

Answer:
""",
        input_variables=[
            "context",
            "question"
        ]
    )

    # ----------------------------------------
    # Format retrieved documents
    # ----------------------------------------

    def format_docs(docs):

        return "\n\n".join(
            doc.page_content
            for doc in docs
        )

    # ----------------------------------------
    # RAG Pipeline
    # ----------------------------------------

    parallel_chain = RunnableParallel({

        "context":
            retriever
            | RunnableLambda(format_docs),

        "question":
            RunnablePassthrough()

    })

    # ----------------------------------------
    # Output Parser
    # ----------------------------------------

    parser = StrOutputParser()

    # ----------------------------------------
    # Complete RAG Chain
    # ----------------------------------------

    main_chain = (
        parallel_chain
        | prompt
        | llm
        | parser
    )

    return main_chain

# ============================================================
# COMPLETE RAG PIPELINE
# ============================================================

def process_video(video_url):

    # ----------------------------------------
    # Extract video ID
    # ----------------------------------------

    video_id = extract_video_id(
        video_url
    )

    if not video_id:
        raise ValueError(
            "Invalid YouTube URL."
        )

    # ----------------------------------------
    # Fetch transcript
    # ----------------------------------------

    transcript = get_transcript(
        video_id
    )

    if not transcript.strip():
        raise ValueError(
            "Transcript is empty."
        )

    # ----------------------------------------
    # Create vector database
    # ----------------------------------------

    vector_store = create_vector_store(
        transcript
    )

    return video_id, vector_store

# ============================================================
# ASK QUESTION
# ============================================================

def ask_question(
    vector_store,
    question
):

    # Create RAG chain
    rag_chain = create_rag_chain(
        vector_store
    )

    # Generate answer
    answer = rag_chain.invoke(
        question
    )

    return answer



